#!/bin/bash

BISONVERSION=2.3

set -ex
cd $(mktemp -d)
curl http://ftp.gnu.org/gnu/bison/bison-${BISONVERSION}.tar.gz -O
tar -xvzf bison-${BISONVERSION}.tar.gz
cd bison-${BISONVERSION}
automake --add-missing || echo whatever
./configure --prefix=/usr/local/bison --with-libiconv-prefix=/usr/local/libiconv/
make all install
